### ISSUE TITLE
[Bug] Polymer support checks for wrong (outdated?) mod ID

### ISSUE THREAD

**Issue by unilock** [Siphalor/spiceoffabric#110]
When `use-polymer` is set to `true` in `spiceoffabric.hjson`, the server crashes with `Polymer is not installed, but Polymer usage is enabled in the Spice of Fabric config!`, regardless of whether Polymer is installed.

I believe this is because the mod is checking for the wrong mod ID for Polymer:

https://github.com/Siphalor/spiceoffabric/blob/7495487b447c3f575f00734d7b5e6c425cce970c/src/main/java/de/siphalor/spiceoffabric/SpiceOfFabric.java#L78-L86

`"polymer"` should be `"polymer-core"`.

(and/or `"polymer-resource-pack"`, but it's technically not required, and it's unlikely that `polymer-core` will ever be installed standalone without `polymer-resource-pack` as part of a bundle)

**Comment by Siphalor** [comment]
Thanks for reporting, it will be fixed in the next release :‌)

**Comment by unilock** [comment]
This is still the case in the latest release for 1.20.4...

https://github.com/Siphalor/spiceoffabric/blob/3590198fa2e1f4d7336681324e17e29a9498ae57/src/main/java/de/siphalor/spiceoffabric/SpiceOfFabric.java#L79

**Comment by cintreck** [comment]
open the issue again please, this isn't fixed

**Comment by Michael-Lim-KH** [comment]
This is not fixed in 1.20.1 releases, same issue as above.

**Comment by Zekiu** [comment]
Still not fixed in 1.20.4

**Comment by AgentK20** [comment]
Still broken in 1.6.2+mc1.20.1 distributed on Modrinth
