### ISSUE TITLE
Configuration not changing

### ISSUE THREAD

**Issue by dranorter** [Siphalor/spiceoffabric#13]
I have a bunch of random mods installed so I'm sure there could be a conflict, but:

I'm changing my Spice of Fabric configuration inside the configuration menu and it's just resetting when I restart Minecraft. Changes seem to persist while I play but not last.

So I tried editing spiceoffabric.hjson, and first of all it only had a "respawn" and "carrot" section. I added the following:

	food: {
		hunger: (hungerValue ^ 1.2) * 0.85 ^ timesEaten
		saturation: max(saturationValue, (saturationValue ^ 2) * 0.5 ^ timesEaten)
	}

Still no effect. The old defaults are all that show in the configuration menu. Nothing I do changes those defaults.

**Comment by Siphalor** [comment]
This might've been due to Siphalor/tweed-api#3.

I'm gonna comment again when a fixed version of SoF is released

**Comment by Siphalor** [comment]
This should be resolved by now
