### ISSUE TITLE
Configurable eating time

### ISSUE THREAD

**Issue by dranorter** [Siphalor/spiceoffabric#14]
It would be really nice to be able to configure eating time via a formula just like hunger value and saturation value.

Two useful setups that come to mind:

(1) Eating time is 1 when the food isn't in your history, and 2 otherwise. This way there's a fairly clear indication that a food was or wasn't new, without eating time getting ridiculous.

(2) Eating time lengthens via the same formula that nutrition shortens. This just seems intuitive.

**Comment by Siphalor** [comment]
When I read your issue I actually wanted to close it because I thought I already did that.

But apparently it's hard coded so thank you for the reminder :)
