### ISSUE TITLE
Obsolete NBT crafting version is used.

### ISSUE THREAD

**Issue by RDKRACZ** [Siphalor/spiceoffabric#17]
Please update this dependency because the version provided by this mod is causing issues with cardinal components API.

**Comment by RDKRACZ** [comment]
And just after you did this they released nbt 2.0.4 haha.

**Comment by Siphalor** [comment]
> And just after you did this they released nbt 2.0.4 haha.

The most funny thing is that "they" is me ^^

NbtC doesn't contain any important fixes so it's not crucial to update.

Also I just released this like a minute ago - how fast did you notice? 😄

**Comment by RDKRACZ** [comment]
> The most funny thing is that "they" is me ^^

Ohhh how didn't I saw this lol.

> how fast did you notice

I'm addicted to checking updates.

**Comment by RDKRACZ** [comment]
Can you add a homepage tag to the fabric.mod.json file pointing to the curseforge page? It's missing.
