### ISSUE TITLE
Disconnect client on connection to server

### ISSUE THREAD

**Issue by itsNordLord** [Siphalor/spiceoffabric#23]
**Issue:** Dedicated Fabric modded server with Spice of Fabric disconnects any clients attempting to connect with a console printout found below. Clients can connect to server with no issue when Spice of Fabric is removed.

**Console log**: https://paste.gg/p/anonymous/d9a41760e1de4e94a435b5d17a46b1d1

**Versions**:
Spice of Fabric: `1.3.2+1.16.4`
Fabric Loader: `0.11.3-1.16.5`

**Dependency Versions**:
Fabric API: `0.32.5-1.16`

**Comment by Siphalor** [comment]
This should:tm: be fixed now.
