### ISSUE TITLE
Config issues in version 1.3.4 for MC 1.17.1

### ISSUE THREAD

**Issue by Danklor** [Siphalor/spiceoffabric#29]
This mod's config icon did not appear in ModMenu (version 2.0.2). Also, I tried copying a config file from a previous working Spice of Fabric and, although there were no errors logged, the carrot mode option did not work and no matter how many unique foods were eaten the heart count would not increase. Full log and tested config file attached.

[spiceoffabric-log.txt](https://github.com/Siphalor/spiceoffabric/files/6795977/spiceoffabric-log.txt)

[spiceoffabric-config.txt](https://github.com/Siphalor/spiceoffabric/files/6795980/spiceoffabric-config.txt)

**Comment by Siphalor** [comment]
Seems like #30 has indeed fixed this :)
