### ISSUE TITLE
Ate a steak (any food item) then crash.

### ISSUE THREAD

**Issue by Gbergz** [Siphalor/spiceoffabric#3]
Title^

This started happening only when i added this mod, but i still don't know if its entirely your mods fault or the Fabric API in 1.14.2 or whatever. 

Have a look at the crash-report:
[Paste.ee](https://paste.ee/p/5YMiD)

Mod Version: 1.2.0-beta.3+1.14.2
MC Version: 1.14.2
Fabric API version: fabric-api-0.3.0+build.175.jar

**Comment by Siphalor** [comment]
`// I blame myself`

**Comment by AK9Official** [comment]
I blame you, you & you @Siphalor

**Comment by Siphalor** [comment]
I honestly love that mod.

(Should be fixed with latest release)
