### ISSUE TITLE
[bug] Carrot mode health level first synchronized after eating food

### ISSUE THREAD

**Issue by TobiPeterG** [Siphalor/spiceoffabric#37]
Hey there,

I play on a private server most of the times and noticed that when I connect after the server just started (so was shut down before), I don't have the hearts of the carrot mode, until I eat something. Then I hear the pling sound and I start to heal to the health level I'd earned.
If wanted, I can provide a screen record

Can this be confirmed? :thinking:

**Comment by TobiPeterG** [comment]
Also happens in single player worlds

**Comment by sweetsosweet** [comment]
Was coming here to post the same (I'm in singleplayer). Also carrot mode doesn't seem to disable normal mode? So food has diminishing returns along with being used to gain hearts. How to disable diminishing returns in carrot mode?

**Comment by TobiPeterG** [comment]
> Was coming here to post the same (I'm in singleplayer). Also carrot mode doesn't seem to disable normal mode? So food has diminishing returns along with being used to gain hearts. How to disable diminishing returns in carrot mode?
> 
> Also forgot to mention, using spiceoffabric-1.4.1+1.17.1.jar

Good to know I'm not the only one! :P

Afaik it is intended that carrot mode doesn't deactivate the normal punishments. And I don't think sof has that functionality yet.

It's probably best if you created a feature request to keep track of it, so it doesn't get buried here.
But it should be an option imo, as e. g. I like to have both.

**Comment by TobiPeterG** [comment]
> > Was coming here to post the same (I'm in singleplayer). Also carrot mode doesn't seem to disable normal mode? So food has diminishing returns along with being used to gain hearts. How to disable diminishing returns in carrot mode?
> > 
> > Also forgot to mention, using spiceoffabric-1.4.1+1.17.1.jar
> 
> Good to know I'm not the only one! :P
> 
> Afaik it is intended that carrot mode doesn't deactivate the normal punishments. And I don't think sof has that functionality yet.
> 
> It would probably be the best if you created a feature request to keep track of it, so it doesn't get buried here.
> But it should be an option imo, as e. g. I like to have both.

**Comment by cutiexe** [comment]
Confirming that this still happens with 1.4.1+1.18-pre5. Really hurts when I have my starting hearts set below 10 and I can't heal until my saturation burns all the way down.

**Comment by rxay579** [comment]
> Good to know I'm not the only one! :P
> 
> Afaik it is intended that carrot mode doesn't deactivate the normal punishments. And I don't think sof has that functionality yet.
> 
> It would probably be the best if you created a feature request to keep track of it, so it doesn't get buried here. But it should be an option (not a this or that) imo, as e.g. I like to have both.

Came here because I also have the issue described by [TobiPeterG](https://github.com/TobiPeterG) while playing on a private local server which is running the slightly customized "Better Minecraft [FABRIC] - 1.18.1" v16.5 modpack.

I didn't see any option in the mod about disabling the negatives when enabling the carrot mode, but since the negative formulas are editable, I just modified those.  For example, to eliminate the penalties, change the formulas:
hunger: hungerValue
consume-duration: consumeDuration
