### ISSUE TITLE
SoF 1.16.5 crash

### ISSUE THREAD

**Issue by nxghtmvrx** [Siphalor/spiceoffabric#40]
[Client crash on start](https://0x0.st/-3KA.txt)
Let me know if this should be reported on the side of other mod instead.

**Comment by Hangenbo** [comment]
Hello, I got the same problem. 

Here's the crash report : [crash-2021-09-18_10.11.39-client.txt](https://github.com/Siphalor/spiceoffabric/files/7189535/crash-2021-09-18_10.11.39-client.txt)

**Comment by nxghtmvrx** [comment]
Version 1.0.11 AppleSkin

**Comment by Siphalor** [comment]
@nxghtmvrx You're pretty right there, but Fabric is not the one to blame ^^

To summarize:

When Spice of Fabric was mainly developed, AppleSkin had no official API that SoF could hook into. Therefor I needed to mixin (adapt the code of) to AppleSkin.

Pretty recently AppleSkin update to 2.0 and with that they changed the related parts of the code and exposed an API.

SoF has the correct changes in the 1.17 version, but I currently do not intend to do backporting for SoF.

If you want to play with both mods, you basically got two options:

1. Update to Minecraft 1.17 and use the latest versions.
2. Stay on Minecraft 1.16 with an AppleSkin version below 2.

**Comment by Siphalor** [comment]
Since we're now three major versions away from Minecraft 1.16, I'm gonna close this issue.
