### ISSUE TITLE
Crash on death syncing carrot mode food history - MC 1.18

### ISSUE THREAD

**Issue by Danklor** [Siphalor/spiceoffabric#41]
I was killed by the ender dragon and then the game crashed with an error syncing food history. Full log attached with all details.

[spicy_death.txt](https://github.com/Siphalor/spiceoffabric/files/7644678/spicy_death.txt)

**Comment by Siphalor** [comment]
That's a beautiful name for the log :P

Thanks for reporting, a fix is coming in the next release.
