### ISSUE TITLE
Health reduces every time i restart game.

### ISSUE THREAD

**Issue by cowsha** [Siphalor/spiceoffabric#48]
Only possible fix is /kill, feels like Carrot mode is on but in fact its off.
I guess something wrong with basehealth thing.
Running on 1.18.2

**Comment by pastellexists** [comment]
Having the same issue, also running on 1.18.2

**Comment by antD97** [comment]
Found a temp fix:
1. Enable carrot mode
2. Set health formula setting to 20

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/58
