### ISSUE TITLE
[bug]game crash

### ISSUE THREAD

**Issue by Rad586** [Siphalor/spiceoffabric#50]
It crashes my modpack in 1.18.1 for some reasons, maybe related to "food history". Below are the log files. Could you please fix that problem? It's really really important to my modpack, thanks!!
[crash-2022-04-22_21.22.04-server.txt](https://github.com/Siphalor/spiceoffabric/files/8541492/crash-2022-04-22_21.22.04-server.txt)
[crash-2022-04-21_09.59.36-server.txt](https://github.com/Siphalor/spiceoffabric/files/8541497/crash-2022-04-21_09.59.36-server.txt)
[crash-2022-04-19_23.34.19-client.txt](https://github.com/Siphalor/spiceoffabric/files/8541499/crash-2022-04-19_23.34.19-client.txt)

**Comment by Siphalor** [comment]
Hey, thanks for reporting the crash.

Can you please try out the latest release coming out later today and see if this is still an issue?

**Comment by Rad233** [comment]
It seemed to be fixed in 1.18.2(however my modpack is 1.18.1😂)

**Comment by Rad586** [comment]
It seemed to be fixed in 1.18.2(however my modpack is 1.18.1😂)
