### ISSUE TITLE
Depecated REI Plugin method

### ISSUE THREAD

**Issue by WebF1yin** [Siphalor/spiceoffabric#60]
Obligatory "first post, let me know if I should add logs or details or stuff"

When launching 1.19.2 with spice of fabric version 1.5.3 and any of the REI versions available for 1.19.2, I am getting an error that rei_plugins_v0 is deprecated and should be replaced with "rei_server" "rei_client" or "rei_common."  For playing single-player, this does not impact gameplay in any way (that I could find). However, a server will not boot because of this exact same error. 

I was able to fix this issue by changing "rei_plugins_v0" on line 27 of fabric.mod.json in the root of the .jar to "rei_common" as suggested by the error message. This fix allowed both the server and client to boot flawlessly, and I was unable to identify any problems in gameplay.

Thanks!

**Comment by Siphalor** [comment]
Thanks for reporting the issue.

This issue has already been reported in #57, I just haven't pushed a release since yet as I thought that issue was non-critical.

Since you reported that it's blocking servers from starting, I'm gonna quickly push a release :)

**Comment by WebF1yin** [comment]
You're the best! 

Thank you <3
