### ISSUE TITLE
Seems to have a conflict with Fabric API 0.67 on 1.19.2

### ISSUE THREAD

**Issue by Abalieno** [Siphalor/spiceoffabric#67]
https://github.com/FabricMC/fabric/issues/2680

The conflict is inside NBT Crafting

**Comment by grace5532** [comment]
I'm sure you already know, but the latest version (2.2.3) of NBTCrating fixes this

**Comment by Siphalor** [comment]
Should be fixed with the latest beta which has full support for 1.19.2 (and also doesn't rely on NbtC anymore)
