### ISSUE TITLE
1.19.2 fabric game crash

### ISSUE THREAD

**Issue by DarkCrystalll** [Siphalor/spiceoffabric#68]
[minecraft-exported-crash-info-2022-11-29T10-39-40.zip](https://github.com/Siphalor/spiceoffabric/files/10109306/minecraft-exported-crash-info-2022-11-29T10-39-40.zip)
when I add this mod,I can't open my game.

**Comment by Siphalor** [comment]
Thanks for reporting this issue, it is already tracked as #67.
