### ISSUE TITLE
[Bug] Lunchbox can be inserted inside Lunchbox

### ISSUE THREAD

**Issue by TheonlyTazz** [Siphalor/spiceoffabric#78]
### Modpack

FTB Legend of the Eyes

### Modpack version

1.0.0

### Modloader version

Fabric - 0.14.12

### Mod Version
spiceoffabric-1.6.0-beta.2+1.19.2.jar

### Log Files

N/A

### Describe the bug

With the lunchbox open, place various food items inside.

If you accidently. (or purposely) shift-click on the lunchbox from your toolbar, it attempts to put the 'lunchbox in the lunchbox' and causes it to instantly despawn from your inventory with ALL the food you just placed inside.

### Steps to reproduce

Craft or otherwise get lunchbox.
put it in your toolbar, and right click on it.
put something inside it like bread, foods, etc.
shift click on the lunch box itself.
watch your hard earned food and sustenance disappear into the vapor 

### Expected behaviour

you shouldn't be able to put a lunchbox in a lunchbox dawg.

### Additional information

[Link to FTB Modpack Issue](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2559)

**Comment by Siphalor** [comment]
Seems like I fixed this in Beta 3 already.
So this is already fixed.

You might want to wait a little with updating as I plan to leave the beta stage with a bunch of other important bug fixes soon™.
