### ISSUE TITLE
Menu traps you forever as of 1.16

### ISSUE THREAD

**Issue by alxpettit** [Siphalor/spiceoffabric#9]
* Accidentally click on menu while you're doing something else
* Click cancel as much as you want, you are not getting out of here.
* Muahahaha. `tweed.cloth.tweed` forever.
* give up and force close MC

Edit: Actually I think this might be something else in my modpack... I'm going to do more testing and reopen if I figure out the problem came from here after all.

**Comment by alxpettit** [comment]
Okay, so I think it's caused by this. If I search for the letter `c` in the modlist thingy, I get trapped instantly. If I spam bksp and Esc at the same time when I get to `tweed.cloth.tweed`, it will take me to the Spice of Life config menu. But sometimes it just takes me out. Weird bug.

**Comment by Siphalor** [comment]
See Siphalor/tweed-api#8

**Comment by alxpettit** [comment]
Whoop, guess I'll close this then and follow the discussion in that issue.
