### ISSUE TITLE
Farmers Delight Nourishment and Comfort Effects are removed entirely 

### ISSUE THREAD

**Issue by Phaserra** [Siphalor/spiceoffabric#90]
Hi, I really like this feature from this mod, and it should remain as a reward for cooking complex dishes from that mod.

I found out removing spice of fabric fixes the issue, though is there a way to reenable this from the config?

**Comment by Siphalor** [comment]
Hi, thanks for reporting this issue :)

This is probably a duplicate of #87, as food effects in general seem to not be working for some people.
