### ISSUE TITLE
Cake Crash

### ISSUE THREAD

**Issue by windlesille** [Siphalor/spiceoffabric#92]
Eating cake (placed down) crashes the game.
MC Version: 1.19.2
Fabric Version: 0.14.21
Spice Of Fabric Version: 1.6.0-beta.4

Crash Log:

[crash.txt](https://github.com/Siphalor/spiceoffabric/files/11752706/crash.txt)

**Comment by Siphalor** [comment]
Thanks for reporting, I'll try to look into it.
As this has already been reported as #89, I'll close this and track it over there ;)
