### ISSUE TITLE
Cake Crashing

### ISSUE THREAD

**Issue by MikeTheBuddy** [Siphalor/spiceoffabric#94]
After experimenting with the mod to run some numbers on the formula used for figuring out when to increase your hp, I ran into an issue when it came to the cake block.

When eating it without having it unlocked, I was capable of eating the first slice, but the next slice seemed to crash the game.

Upon reloading the world, attempting to eat the cake again would crash my game.

Removing the cake for a new one would make that cake impossible to eat, where it would just keep reappearing and updating back to a pre-eaten state. 

Resetting progress on the carrot tracker would just lead to the cake crash once more.

It so far has only happened with the cake block.

(Copy of the Crash Report)
[crash-2023-06-18_08.37.50-client.txt](https://github.com/Siphalor/spiceoffabric/files/11781692/crash-2023-06-18_08.37.50-client.txt)

**Comment by Siphalor** [comment]
Hey thanks for reporring :)

This issue has already been reported as #89 and will be fixed with the next release.
