### ISSUE TITLE
Enable French translation

### ISSUE THREAD

**Issue by edgarogh** [Siphalor/spiceoffabric#97]
Hello, I'd like to translate this mod into French but the language doesn't exist yet and I think there's a permission issue when [I](https://weblate.siphalor.de/user/edgarogh/) try to create it:

`Your request was rejected because you have performed too many operations recently. Please try again later. `

Could you open a blank translation yourself?

**Comment by Siphalor** [comment]
Not sure what the issue was, but I created the French translation in Weblate: https://weblate.siphalor.de/projects/spice-of-fabric/spice-of-fabric/fr_FR/
